name: Weekly GitHub Scraper Run

on:
  schedule:
    # adjust cron as needed; this example runs every Monday at 02:00 UTC
    - cron: "0 2 * * 1"
  workflow_dispatch: # manual trigger possible too

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Write .env from secrets
        run: |
          echo "ES_APIKEY=${{ secrets.ES_APIKEY }}" >> .env
          echo "ES_ENDPOINT=${{ secrets.ES_ENDPOINT }}" >> .env
          echo "ES_INDEX=${{ secrets.ES_INDEX }}" >> .env
          echo "PRIVATE_GITHUB_TOKEN=${{ secrets.PRIVATE_GITHUB_TOKEN }}" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT///$'\\n' }}" > .env

      - name: Build scraper
        run: cargo build --release

      - name: Run scraper
        run: cargo run --release
