name: Weekly GitHub Scraper Run

on:
  schedule:
    # adjust cron as needed; this example runs every Monday at 02:00 UTC
    - cron: "0 2 * * 1"
  workflow_dispatch: # manual trigger possible too

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ES_APIKEY: ${{ secrets.ES_APIKEY }}
      ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
      ES_INDEX: ${{ secrets.ES_INDEX }}
      PRIVATE_GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      # add as many as you need

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build scraper
        run: cargo build --release

      - name: Run scraper
        run: cargo run --release
